swagger: '2.0'
info:
  title: 'API chat'
  description: 'API per la gestione di una chat'
  version: 1.0.0
definitions:

  ModificaMessaggio:
    type: object
    required:
      - data
    properties:
      data:
        type: string
        description: 'data aggiornata'
        example: '01-11-2004'

  Messaggio:
    type: object
    required:
      - id 
      - data
      - autore
      - testo
    properties:
      id:
        type: string
        description: 'id del messaggio'
      data:
        type: string
        description: 'data del messaggio'
        example: '12-12-2004'  
      autore:
        type: string
        description: 'autore del messaggio'
      testo:
        type: string
        description: 'testo del messaggio'

  Stanza:
    type: object
    required:
      - id
      - data
      - messaggi
    properties:
      id:
        type: string
        description: 'id della stanza'
      data:
        type: string
        example: '12-12-2004'
        description: 'data della stanza'
      messaggi:
        type: array
        items:
          $ref: '#/definitions/Messaggio'

paths:
  /{idStanza}/messaggi/{autore}:
    delete:
      summary: 'cancellare i messaggi scritti da un autore'
      operationId: 'cancellaMessaggi'
      parameters:
        - name: idStanza
          in: path
          required: true
          type: string
          description: 'id della stanza'
        
        - name: autore
          in: path
          type: string
          required: true
          description: 'nome autore'

      responses:
        '200':
          description: 'cancellati con successo'
          schema: #bastava anche solo la parte schema ref
            type: array
            items:
              $ref: '#/definitions/Messaggio'
        '400':
          description: 'errore'
  /{idStanza}/messaggio:
    post:
      summary: 'aggiungo un nuovo messaggio a una stanza'
      operationId: 'addMessaggio'
      parameters:
        - name: messaggio
          in: body
          required: true
          schema:
            $ref:  '#/definitions/Messaggio'
          description: 'messaggio da aggiungere'
        - name: idStanza
          in: path
          required: true
          type: string
          description: 'id della stanza'

      responses:
        '201':
          description: 'messaggio aggiunto correttamente'
          schema:
            $ref: '#/definitions/Messaggio'
        '400':
          description: 'errore'

  /{idStanza}/{idMessaggio}:
    put:
      summary: 'modifico la data di pubblicazione di un messaggio'
      operationId: 'modificaMessaggio'
      parameters:
        - name: idStanza
          in: path
          required: true
          type: string
          description: 'id della stanza'
        - name: idMessaggio
          in: path
          required: true
          type: string
          description: 'id del messaggio'
        - name: body   
          in: body     # quando in= body non ci vuole type solo schema
          required: true
          description: 'modifica del messaggio'
          schema:
            $ref: '#/definitions/ModificaMessaggio'
      responses:
        '200':
          description: 'modifica corretta'
          schema:
            $ref: '#/definitions/ModificaMessaggio'
        '400':
          description: 'errore'


           