swagger: '2.0'
info:
  description: 'API gestione di un blog di botanica'
  title: 'API Blog Botanica'
  version: 1.0.0
definitions:
  Articolo:
    type: object 
    required:
      - id
      - dataPubblicazione
      - titolo
      - contenuto
      - categorie
    properties:
      id:
        type: integer
        minimum: 0
      dataPubblicazione:
        type: string
        example: '22-12-2003'
      titolo: 
        type: string
        example: 'Garofani'
      contenuto:
        type: string
        example: 'Sono alti'
      categorie:
        #può appartenere a una o più categorie questo 
        #non è un enum pk enum è soltanto una categoria penso
        type: array
        items:
          type: string
          enum:
            - 'orto'
            - 'fiori'
            - 'consigli'
            - 'attrezzi'
            - 'prodotti'
            - 'news'

paths:
  /articoli:
    get:
      summary: 'ottenere l elenco di tutti gli articoli di una data categoria e pubblicati dopo una certa data' 
      operationId: 'elencoArticoli'
      parameters:
        - name: minData
          in: query
          required: true
          description: 'data minima'
          type: string
         
        
        - name: categoria
          in: query
          required: true
          description: 'categoria degli articoli'
          type: string
          enum: 
            - 'orto'
            - 'fiori'
            - 'consigli'
            - 'attrezzi'
            - 'prodotti'
            - 'news'
          
      responses:
        '200': 
          description: 'successo'
          schema:
            type: array
            items:
              $ref: '#/definitions/Articolo'
        '400':
          description: 'errore'
    
    post:
      summary: 'Aggiungere un nuovo articolo'
      operationId: 'aggiungiArticolo'
      parameters:
        - name: articolo
          in: body
          required: true
          description: 'aggiungi articolo'
          schema:
            $ref: '#/definitions/Articolo'
      responses:
        '201':
          description: 'creato correttmamente'
          schema:
             $ref: '#/definitions/Articolo'
        '400':
          description: 'errore'
  /articoli/{articoloId}:
      put:
        summary: 'Modificare il contenuto di un articolo'
        operationId: 'modificaArticolo'
        parameters:
          - name: articoloId
            required: true
            in: path
            type: integer
            description: 'id dell articolo da aggiornare'
            
          - name: body
            required: true
            in: body
            description: 'Nuovo contenuto dell articolo'
            schema:
              type: object  # ERRORE: stai passando solo il contenuto, non l'intero Articolo (questo è corretto)
              required:
                - contenuto
              properties:
                contenuto:
                  type: string
                  example: 'Nuovo contenuto aggiornato'
        responses:
          '200':
            description: 'modifica con successo'
            schema:
              $ref: '#/definitions/Articolo'
            examples:
              application/json:
                id: 123
                dataPubblicazione: '15-12-2002'
                titolo: 'Fiori Gialli'
                contenuto: 'Contenuto'
                categorie: ['fiori','consigli']
          '400':
            description: 'errore'
    